export const START_DELAY_MILLISECONDS = 5 * 1000;
export const WRONG_DELAY_MILLISECONDS = 2 * 1000;
export const PRIME_NUMBER_START = 1;
export const PRIME_NUMBER_END = 50;
export const PRIME_NUMBER_MAX_COUNT = 15;
